### ISSUE TITLE
Add documentation to project

### ISSUE THREAD

**Issue by Math-Morin** [Crodirodiroum/Jasmin.jl#7]
# Add documentation to project

### DESCRIPTION:
Whole project needs to be better documented. Having better doc should help development, make life easier for newcomers and reduce the amount of questions asked to Jean.
    
---

## TASKS :
- [ ] Add comments to code so it becomes self-explanatory.
- [ ] #10
- [ ] Supplement and complete top level README.md.
- [ ] #8
- [ ] Create document explaining, in broad lines, how Jasmin works, as well as the scope and goals of the project.

Development for this user story is found on branch `story/7-add-documentation-to-project`.
